# Anna KaRNNa

In this notebook, I'll build a character-wise RNN trained on Anna Karenina, one of my all-time favorite books. It'll be able to generate new text based on the text from the book.

This network is based off of Andrej Karpathy's [post on RNNs](http://karpathy.github.io/2015/05/21/rnn-effectiveness/) and [implementation in Torch](https://github.com/karpathy/char-rnn). Also, some information [here at r2rt](http://r2rt.com/recurrent-neural-networks-in-tensorflow-ii.html) and from [Sherjil Ozair](https://github.com/sherjilozair/char-rnn-tensorflow) on GitHub. Below is the general architecture of the character-wise RNN.

<img src="assets/charseq.jpeg" width="500">

In [1]:
import time
from collections import namedtuple

import numpy as np
import tensorflow as tf

First we'll load the text file and convert it into integers for our network to use. Here I'm creating a couple dictionaries to convert the characters to and from integers. Encoding the characters as integers makes it easier to use as input in the network.

In [2]:
with open('anna.txt', 'r') as f:
    text=f.read()
vocab = set(text)
vocab_to_int = {c: i for i, c in enumerate(vocab)}
int_to_vocab = dict(enumerate(vocab))
encoded = np.array([vocab_to_int[c] for c in text], dtype=np.int32)

Let's check out the first 100 characters, make sure everything is peachy. According to the [American Book Review](http://americanbookreview.org/100bestlines.asp), this is the 6th best first line of a book ever.

In [3]:
text[:100]

'Chapter 1\n\n\nHappy families are all alike; every unhappy family is unhappy in its own\nway.\n\nEverythin'

And we can see the characters encoded as integers.

In [4]:
encoded[:100]

array([25, 51, 34,  9, 47,  0, 10, 15, 14, 40, 40, 40, 36, 34,  9,  9, 50,
       15, 59, 34, 31, 74, 23, 74,  0, 17, 15, 34, 10,  0, 15, 34, 23, 23,
       15, 34, 23, 74, 19,  0, 80, 15,  0, 77,  0, 10, 50, 15, 64, 13, 51,
       34,  9,  9, 50, 15, 59, 34, 31, 74, 23, 50, 15, 74, 17, 15, 64, 13,
       51, 34,  9,  9, 50, 15, 74, 13, 15, 74, 47, 17, 15, 75, 81, 13, 40,
       81, 34, 50, 46, 40, 40, 72, 77,  0, 10, 50, 47, 51, 74, 13])

Since the network is working with individual characters, it's similar to a classification problem in which we are trying to predict the next character from the previous text.  Here's how many 'classes' our network has to pick from.

In [5]:
len(vocab)

83

## Making training mini-batches

Here is where we'll make our mini-batches for training. Remember that we want our batches to be multiple sequences of some desired number of sequence steps. Considering a simple example, our batches would look like this:

<img src="assets/sequence_batching@1x.png" width=500px>


<br>
We have our text encoded as integers as one long array in `encoded`. Let's create a function that will give us an iterator for our batches. I like using [generator functions](https://jeffknupp.com/blog/2013/04/07/improve-your-python-yield-and-generators-explained/) to do this. Then we can pass `encoded` into this function and get our batch generator.

The first thing we need to do is discard some of the text so we only have completely full batches. Each batch contains $N \times M$ characters, where $N$ is the batch size (the number of sequences) and $M$ is the number of steps. Then, to get the number of batches we can make from some array `arr`, you divide the length of `arr` by the batch size. Once you know the number of batches and the batch size, you can get the total number of characters to keep.

After that, we need to split `arr` into $N$ sequences. You can do this using `arr.reshape(size)` where `size` is a tuple containing the dimensions sizes of the reshaped array. We know we want $N$ sequences (`n_seqs` below), let's make that the size of the first dimension. For the second dimension, you can use `-1` as a placeholder in the size, it'll fill up the array with the appropriate data for you. After this, you should have an array that is $N \times (M * K)$ where $K$ is the number of batches.

Now that we have this array, we can iterate through it to get our batches. The idea is each batch is a $N \times M$ window on the array. For each subsequent batch, the window moves over by `n_steps`. We also want to create both the input and target arrays. Remember that the targets are the inputs shifted over one character. You'll usually see the first input character used as the last target character, so something like this:
```python
y[:, :-1], y[:, -1] = x[:, 1:], x[:, 0]
```
where `x` is the input batch and `y` is the target batch.

The way I like to do this window is use `range` to take steps of size `n_steps` from $0$ to `arr.shape[1]`, the total number of steps in each sequence. That way, the integers you get from `range` always point to the start of a batch, and each window is `n_steps` wide.

In [6]:
def get_batches(arr, n_seqs, n_steps):
    '''Create a generator that returns batches of size
       n_seqs x n_steps from arr.
       
       Arguments
       ---------
       arr: Array you want to make batches from
       n_seqs: Batch size, the number of sequences per batch
       n_steps: Number of sequence steps per batch
    '''
    # Get the batch size and number of batches we can make
    batch_size = n_seqs * n_steps
    n_batches = len(arr)//batch_size
    
    # Keep only enough characters to make full batches
    arr = arr[:n_batches * batch_size]
    
    # Reshape into n_seqs rows
    arr = arr.reshape((n_seqs, -1))
    
    for n in range(0, arr.shape[1], n_steps):
        # The features
        x = arr[:, n:n+n_steps]
        # The targets, shifted by one
        y = np.zeros_like(x)
        y[:, :-1], y[:, -1] = x[:, 1:], x[:, 0]
        yield x, y

Now I'll make my data sets and we can check out what's going on here. Here I'm going to use a batch size of 10 and 50 sequence steps.

In [7]:
batches = get_batches(encoded, 10, 50)
x, y = next(batches)

In [8]:
print('x\n', x[:10, :10])
print('\ny\n', y[:10, :10])

x
 [[25 51 34  9 47  0 10 15 14 40]
 [15 34 31 15 13 75 47 15 29 75]
 [77 74 13 46 40 40 79 43  0 17]
 [13 15 20 64 10 74 13 29 15 51]
 [15 74 47 15 74 17 55 15 17 74]
 [15  5 47 15 81 34 17 40 75 13]
 [51  0 13 15 54 75 31  0 15 59]
 [80 15 52 64 47 15 13 75 81 15]
 [47 15 74 17 13 44 47 46 15 42]
 [15 17 34 74 20 15 47 75 15 51]]

y
 [[51 34  9 47  0 10 15 14 40 40]
 [34 31 15 13 75 47 15 29 75 74]
 [74 13 46 40 40 79 43  0 17 55]
 [15 20 64 10 74 13 29 15 51 74]
 [74 47 15 74 17 55 15 17 74 10]
 [ 5 47 15 81 34 17 40 75 13 23]
 [ 0 13 15 54 75 31  0 15 59 75]
 [15 52 64 47 15 13 75 81 15 17]
 [15 74 17 13 44 47 46 15 42 51]
 [17 34 74 20 15 47 75 15 51  0]]


If you implemented `get_batches` correctly, the above output should look something like 
```
x
 [[55 63 69 22  6 76 45  5 16 35]
 [ 5 69  1  5 12 52  6  5 56 52]
 [48 29 12 61 35 35  8 64 76 78]
 [12  5 24 39 45 29 12 56  5 63]
 [ 5 29  6  5 29 78 28  5 78 29]
 [ 5 13  6  5 36 69 78 35 52 12]
 [63 76 12  5 18 52  1 76  5 58]
 [34  5 73 39  6  5 12 52 36  5]
 [ 6  5 29 78 12 79  6 61  5 59]
 [ 5 78 69 29 24  5  6 52  5 63]]

y
 [[63 69 22  6 76 45  5 16 35 35]
 [69  1  5 12 52  6  5 56 52 29]
 [29 12 61 35 35  8 64 76 78 28]
 [ 5 24 39 45 29 12 56  5 63 29]
 [29  6  5 29 78 28  5 78 29 45]
 [13  6  5 36 69 78 35 52 12 43]
 [76 12  5 18 52  1 76  5 58 52]
 [ 5 73 39  6  5 12 52 36  5 78]
 [ 5 29 78 12 79  6 61  5 59 63]
 [78 69 29 24  5  6 52  5 63 76]]
 ```
 although the exact numbers will be different. Check to make sure the data is shifted over one step for `y`.

## Building the model

Below is where you'll build the network. We'll break it up into parts so it's easier to reason about each bit. Then we can connect them up into the whole network.

<img src="assets/charRNN.png" width=500px>


### Inputs

First off we'll create our input placeholders. As usual we need placeholders for the training data and the targets. We'll also create a placeholder for dropout layers called `keep_prob`.

In [9]:
def build_inputs(batch_size, num_steps):
    ''' Define placeholders for inputs, targets, and dropout 
    
        Arguments
        ---------
        batch_size: Batch size, number of sequences per batch
        num_steps: Number of sequence steps in a batch
        
    '''
    # Declare placeholders we'll feed into the graph
    inputs = tf.placeholder(tf.int32, [batch_size, num_steps], name='inputs')
    targets = tf.placeholder(tf.int32, [batch_size, num_steps], name='targets')
    
    # Keep probability placeholder for drop out layers
    keep_prob = tf.placeholder(tf.float32, name='keep_prob')
    
    return inputs, targets, keep_prob

### LSTM Cell

Here we will create the LSTM cell we'll use in the hidden layer. We'll use this cell as a building block for the RNN. So we aren't actually defining the RNN here, just the type of cell we'll use in the hidden layer.

We first create a basic LSTM cell with

```python
lstm = tf.contrib.rnn.BasicLSTMCell(num_units)
```

where `num_units` is the number of units in the hidden layers in the cell. Then we can add dropout by wrapping it with 

```python
tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
```
You pass in a cell and it will automatically add dropout to the inputs or outputs. Finally, we can stack up the LSTM cells into layers with [`tf.contrib.rnn.MultiRNNCell`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/contrib/rnn/MultiRNNCell). With this, you pass in a list of cells and it will send the output of one cell into the next cell. For example,

```python
tf.contrib.rnn.MultiRNNCell([cell]*num_layers)
```

This might look a little weird if you know Python well because this will create a list of the same `cell` object. However, TensorFlow will create different weight matrices for all `cell` objects. Even though this is actually multiple LSTM cells stacked on each other, you can treat the multiple layers as one cell.

We also need to create an initial cell state of all zeros. This can be done like so

```python
initial_state = cell.zero_state(batch_size, tf.float32)
```

Below, we implement the `build_lstm` function to create these LSTM cells and the initial state.

In [10]:
def build_lstm(lstm_size, num_layers, batch_size, keep_prob):
    ''' Build LSTM cell.
    
        Arguments
        ---------
        keep_prob: Scalar tensor (tf.placeholder) for the dropout keep probability
        lstm_size: Size of the hidden layers in the LSTM cells
        num_layers: Number of LSTM layers
        batch_size: Batch size

    '''
    ### Build the LSTM Cell
    # Use a basic LSTM cell
    lstm = tf.contrib.rnn.BasicLSTMCell(lstm_size)
    
    # Add dropout to the cell outputs
    drop = tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob = keep_prob)
    
    # Stack up multiple LSTM layers, for deep learning
    cell = tf.contrib.rnn.MultiRNNCell([tf.contrib.rnn.DropoutWrapper(tf.contrib.rnn.BasicLSTMCell(lstm_size), output_keep_prob = keep_prob) for _ in range(num_layers)])
    initial_state = cell.zero_state(batch_size, tf.float32)
    
    return cell, initial_state

### RNN Output

Here we'll create the output layer. We need to connect the output of the RNN cells to a full connected layer with a softmax output. The softmax output gives us a probability distribution we can use to predict the next character.

If our input has batch size $N$, number of steps $M$, and the hidden layer has $L$ hidden units, then the output is a 3D tensor with size $N \times M \times L$. The output of each LSTM cell has size $L$, we have $M$ of them, one for each sequence step, and we have $N$ sequences. So the total size is $N \times M \times L$.

We are using the same fully connected layer, the same weights, for each of the outputs. Then, to make things easier, we should reshape the outputs into a 2D tensor with shape $(M * N) \times L$. That is, one row for each sequence and step, where the values of each row are the output from the LSTM cells.

One we have the outputs reshaped, we can do the matrix multiplication with the weights. We need to wrap the weight and bias variables in a variable scope with `tf.variable_scope(scope_name)` because there are weights being created in the LSTM cells. TensorFlow will throw an error if the weights created here have the same names as the weights created in the LSTM cells, which they will be default. To avoid this, we wrap the variables in a variable scope so we can give them unique names.

In [11]:
def build_output(lstm_output, in_size, out_size):
    ''' Build a softmax layer, return the softmax output and logits.
    
        Arguments
        ---------
        
        x: Input tensor
        in_size: Size of the input tensor, for example, size of the LSTM cells
        out_size: Size of this softmax layer
    
    '''

    # Reshape output so it's a bunch of rows, one row for each step for each sequence.
    # That is, the shape should be batch_size*num_steps rows by lstm_size columns
    seq_output = tf.concat(lstm_output, axis=1)
    x = tf.reshape(seq_output, [-1, in_size])
    
    # Connect the RNN outputs to a softmax layer
    with tf.variable_scope('softmax'):
        softmax_w = tf.Variable(tf.truncated_normal((in_size, out_size), stddev=0.1))
        softmax_b = tf.Variable(tf.zeros(out_size))
    
    # Since output is a bunch of rows of RNN cell outputs, logits will be a bunch
    # of rows of logit outputs, one for each step and sequence
    logits = tf.matmul(x, softmax_w) + softmax_b
    
    # Use softmax to get the probabilities for predicted characters
    out = tf.nn.softmax(logits, name='predictions')
    
    return out, logits

### Training loss

Next up is the training loss. We get the logits and targets and calculate the softmax cross-entropy loss. First we need to one-hot encode the targets, we're getting them as encoded characters. Then, reshape the one-hot targets so it's a 2D tensor with size $(M*N) \times C$ where $C$ is the number of classes/characters we have. Remember that we reshaped the LSTM outputs and ran them through a fully connected layer with $C$ units. So our logits will also have size $(M*N) \times C$.

Then we run the logits and targets through `tf.nn.softmax_cross_entropy_with_logits` and find the mean to get the loss.

In [12]:
def build_loss(logits, targets, lstm_size, num_classes):
    ''' Calculate the loss from the logits and the targets.
    
        Arguments
        ---------
        logits: Logits from final fully connected layer
        targets: Targets for supervised learning
        lstm_size: Number of LSTM hidden units
        num_classes: Number of classes in targets
        
    '''
    
    # One-hot encode targets and reshape to match logits, one row per batch_size per step
    y_one_hot = tf.one_hot(targets, num_classes)
    y_reshaped = tf.reshape(y_one_hot, logits.get_shape())
    
    # Softmax cross entropy loss
    loss = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=y_reshaped)
    loss = tf.reduce_mean(loss)
    return loss

### Optimizer

Here we build the optimizer. Normal RNNs have have issues gradients exploding and disappearing. LSTMs fix the disappearance problem, but the gradients can still grow without bound. To fix this, we can clip the gradients above some threshold. That is, if a gradient is larger than that threshold, we set it to the threshold. This will ensure the gradients never grow overly large. Then we use an AdamOptimizer for the learning step.

In [13]:
def build_optimizer(loss, learning_rate, grad_clip):
    ''' Build optmizer for training, using gradient clipping.
    
        Arguments:
        loss: Network loss
        learning_rate: Learning rate for optimizer
    
    '''
    
    # Optimizer for training, using gradient clipping to control exploding gradients
    tvars = tf.trainable_variables()
    grads, _ = tf.clip_by_global_norm(tf.gradients(loss, tvars), grad_clip)
    train_op = tf.train.AdamOptimizer(learning_rate)
    optimizer = train_op.apply_gradients(zip(grads, tvars))
    
    return optimizer

### Build the network

Now we can put all the pieces together and build a class for the network. To actually run data through the LSTM cells, we will use [`tf.nn.dynamic_rnn`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/nn/dynamic_rnn). This function will pass the hidden and cell states across LSTM cells appropriately for us. It returns the outputs for each LSTM cell at each step for each sequence in the mini-batch. It also gives us the final LSTM state. We want to save this state as `final_state` so we can pass it to the first LSTM cell in the the next mini-batch run. For `tf.nn.dynamic_rnn`, we pass in the cell and initial state we get from `build_lstm`, as well as our input sequences. Also, we need to one-hot encode the inputs before going into the RNN. 

In [14]:
class CharRNN:
    
    def __init__(self, num_classes, batch_size=64, num_steps=50, 
                       lstm_size=128, num_layers=2, learning_rate=0.001, 
                       grad_clip=5, sampling=False):
    
        # When we're using this network for sampling later, we'll be passing in
        # one character at a time, so providing an option for that
        if sampling == True:
            batch_size, num_steps = 1, 1
        else:
            batch_size, num_steps = batch_size, num_steps

        tf.reset_default_graph()
        
        # Build the input placeholder tensors
        self.inputs, self.targets, self.keep_prob = build_inputs(batch_size, num_steps)

        # Build the LSTM cell
        cell, self.initial_state = build_lstm(lstm_size, num_layers, batch_size, self.keep_prob)

        ### Run the data through the RNN layers
        # First, one-hot encode the input tokens
        x_one_hot = tf.one_hot(self.inputs, num_classes)
        
        # Run each sequence step through the RNN and collect the outputs
        outputs, state = tf.nn.dynamic_rnn(cell, x_one_hot, initial_state=self.initial_state)
        self.final_state = state
        
        # Get softmax predictions and logits
        self.prediction, self.logits = build_output(outputs, lstm_size, num_classes)
        
        # Loss and optimizer (with gradient clipping)
        self.loss = build_loss(self.logits, self.targets, lstm_size, num_classes)
        self.optimizer = build_optimizer(self.loss, learning_rate, grad_clip)

## Hyperparameters

Here I'm defining the hyperparameters for the network. 

* `batch_size` - Number of sequences running through the network in one pass.
* `num_steps` - Number of characters in the sequence the network is trained on. Larger is better typically, the network will learn more long range dependencies. But it takes longer to train. 100 is typically a good number here.
* `lstm_size` - The number of units in the hidden layers.
* `num_layers` - Number of hidden LSTM layers to use
* `learning_rate` - Learning rate for training
* `keep_prob` - The dropout keep probability when training. If you're network is overfitting, try decreasing this.

Here's some good advice from Andrej Karpathy on training the network. I'm going to copy it in here for your benefit, but also link to [where it originally came from](https://github.com/karpathy/char-rnn#tips-and-tricks).

> ## Tips and Tricks

>### Monitoring Validation Loss vs. Training Loss
>If you're somewhat new to Machine Learning or Neural Networks it can take a bit of expertise to get good models. The most important quantity to keep track of is the difference between your training loss (printed during training) and the validation loss (printed once in a while when the RNN is run on the validation data (by default every 1000 iterations)). In particular:

> - If your training loss is much lower than validation loss then this means the network might be **overfitting**. Solutions to this are to decrease your network size, or to increase dropout. For example you could try dropout of 0.5 and so on.
> - If your training/validation loss are about equal then your model is **underfitting**. Increase the size of your model (either number of layers or the raw number of neurons per layer)

> ### Approximate number of parameters

> The two most important parameters that control the model are `lstm_size` and `num_layers`. I would advise that you always use `num_layers` of either 2/3. The `lstm_size` can be adjusted based on how much data you have. The two important quantities to keep track of here are:

> - The number of parameters in your model. This is printed when you start training.
> - The size of your dataset. 1MB file is approximately 1 million characters.

>These two should be about the same order of magnitude. It's a little tricky to tell. Here are some examples:

> - I have a 100MB dataset and I'm using the default parameter settings (which currently print 150K parameters). My data size is significantly larger (100 mil >> 0.15 mil), so I expect to heavily underfit. I am thinking I can comfortably afford to make `lstm_size` larger.
> - I have a 10MB dataset and running a 10 million parameter model. I'm slightly nervous and I'm carefully monitoring my validation loss. If it's larger than my training loss then I may want to try to increase dropout a bit and see if that helps the validation loss.

> ### Best models strategy

>The winning strategy to obtaining very good models (if you have the compute time) is to always err on making the network larger (as large as you're willing to wait for it to compute) and then try different dropout values (between 0,1). Whatever model has the best validation performance (the loss, written in the checkpoint filename, low is good) is the one you should use in the end.

>It is very common in deep learning to run many different models with many different hyperparameter settings, and in the end take whatever checkpoint gave the best validation performance.

>By the way, the size of your training and validation splits are also parameters. Make sure you have a decent amount of data in your validation set or otherwise the validation performance will be noisy and not very informative.


In [15]:
batch_size = 100        # Sequences per batch
num_steps = 100         # Number of sequence steps per batch
lstm_size = 512         # Size of hidden layers in LSTMs
num_layers = 2          # Number of LSTM layers
learning_rate = 0.001   # Learning rate
keep_prob = 0.5         # Dropout keep probability

## Time for training

This is typical training code, passing inputs and targets into the network, then running the optimizer. Here we also get back the final LSTM state for the mini-batch. Then, we pass that state back into the network so the next batch can continue the state from the previous batch. And every so often (set by `save_every_n`) I save a checkpoint.

Here I'm saving checkpoints with the format

`i{iteration number}_l{# hidden layer units}.ckpt`

In [ ]:
epochs = 20
# Save every N iterations
save_every_n = 200

model = CharRNN(len(vocab), batch_size=batch_size, num_steps=num_steps,
                lstm_size=lstm_size, num_layers=num_layers, 
                learning_rate=learning_rate)

saver = tf.train.Saver(max_to_keep=100)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    # Use the line below to load a checkpoint and resume training
    #saver.restore(sess, 'checkpoints/______.ckpt')
    counter = 0
    for e in range(epochs):
        # Train network
        new_state = sess.run(model.initial_state)
        loss = 0
        for x, y in get_batches(encoded, batch_size, num_steps):
            counter += 1
            start = time.time()
            feed = {model.inputs: x,
                    model.targets: y,
                    model.keep_prob: keep_prob,
                    model.initial_state: new_state}
            batch_loss, new_state, _ = sess.run([model.loss, 
                                                 model.final_state, 
                                                 model.optimizer], 
                                                 feed_dict=feed)
            
            end = time.time()
            print('Epoch: {}/{}... '.format(e+1, epochs),
                  'Training Step: {}... '.format(counter),
                  'Training loss: {:.4f}... '.format(batch_loss),
                  '{:.4f} sec/batch'.format((end-start)))
        
            if (counter % save_every_n == 0):
                saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))
    
    saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))

Epoch: 1/20...  Training Step: 1...  Training loss: 4.4197...  3.3513 sec/batch
Epoch: 1/20...  Training Step: 2...  Training loss: 4.3342...  3.4775 sec/batch
Epoch: 1/20...  Training Step: 3...  Training loss: 3.8421...  3.5128 sec/batch
Epoch: 1/20...  Training Step: 4...  Training loss: 4.6431...  3.6463 sec/batch
Epoch: 1/20...  Training Step: 5...  Training loss: 3.9862...  3.7438 sec/batch
Epoch: 1/20...  Training Step: 6...  Training loss: 3.8615...  3.8254 sec/batch
Epoch: 1/20...  Training Step: 7...  Training loss: 3.7402...  3.3912 sec/batch
Epoch: 1/20...  Training Step: 8...  Training loss: 3.5806...  3.4330 sec/batch
Epoch: 1/20...  Training Step: 9...  Training loss: 3.4596...  3.4008 sec/batch
Epoch: 1/20...  Training Step: 10...  Training loss: 3.4313...  3.3913 sec/batch
Epoch: 1/20...  Training Step: 11...  Training loss: 3.4169...  3.4428 sec/batch
Epoch: 1/20...  Training Step: 12...  Training loss: 3.4103...  3.4912 sec/batch
Epoch: 1/20...  Training Step: 13... 

Epoch: 1/20...  Training Step: 103...  Training loss: 3.0630...  4.4766 sec/batch
Epoch: 1/20...  Training Step: 104...  Training loss: 3.0531...  4.5187 sec/batch
Epoch: 1/20...  Training Step: 105...  Training loss: 3.0464...  4.4947 sec/batch
Epoch: 1/20...  Training Step: 106...  Training loss: 3.0430...  4.4815 sec/batch
Epoch: 1/20...  Training Step: 107...  Training loss: 3.0263...  4.5729 sec/batch
Epoch: 1/20...  Training Step: 108...  Training loss: 3.0557...  4.4994 sec/batch
Epoch: 1/20...  Training Step: 109...  Training loss: 3.0407...  4.4562 sec/batch
Epoch: 1/20...  Training Step: 110...  Training loss: 2.9965...  4.4683 sec/batch
Epoch: 1/20...  Training Step: 111...  Training loss: 3.0181...  4.4343 sec/batch
Epoch: 1/20...  Training Step: 112...  Training loss: 3.0142...  4.4455 sec/batch
Epoch: 1/20...  Training Step: 113...  Training loss: 2.9891...  4.4740 sec/batch
Epoch: 1/20...  Training Step: 114...  Training loss: 2.9682...  4.4644 sec/batch
Epoch: 1/20...  

Epoch: 2/20...  Training Step: 203...  Training loss: 2.4651...  4.4979 sec/batch
Epoch: 2/20...  Training Step: 204...  Training loss: 2.4660...  4.5245 sec/batch
Epoch: 2/20...  Training Step: 205...  Training loss: 2.4671...  4.6551 sec/batch
Epoch: 2/20...  Training Step: 206...  Training loss: 2.4642...  4.4711 sec/batch
Epoch: 2/20...  Training Step: 207...  Training loss: 2.4770...  4.6516 sec/batch
Epoch: 2/20...  Training Step: 208...  Training loss: 2.4495...  4.5679 sec/batch
Epoch: 2/20...  Training Step: 209...  Training loss: 2.4456...  4.6128 sec/batch
Epoch: 2/20...  Training Step: 210...  Training loss: 2.4530...  4.5450 sec/batch
Epoch: 2/20...  Training Step: 211...  Training loss: 2.4412...  4.4589 sec/batch
Epoch: 2/20...  Training Step: 212...  Training loss: 2.4761...  4.4691 sec/batch
Epoch: 2/20...  Training Step: 213...  Training loss: 2.4447...  4.5429 sec/batch
Epoch: 2/20...  Training Step: 214...  Training loss: 2.4500...  4.5302 sec/batch
Epoch: 2/20...  

Epoch: 2/20...  Training Step: 303...  Training loss: 2.2346...  4.7386 sec/batch
Epoch: 2/20...  Training Step: 304...  Training loss: 2.2479...  4.7729 sec/batch
Epoch: 2/20...  Training Step: 305...  Training loss: 2.2406...  5.5059 sec/batch
Epoch: 2/20...  Training Step: 306...  Training loss: 2.2705...  5.3657 sec/batch
Epoch: 2/20...  Training Step: 307...  Training loss: 2.2699...  4.7362 sec/batch
Epoch: 2/20...  Training Step: 308...  Training loss: 2.2302...  4.5480 sec/batch
Epoch: 2/20...  Training Step: 309...  Training loss: 2.2494...  4.5194 sec/batch
Epoch: 2/20...  Training Step: 310...  Training loss: 2.2641...  4.5068 sec/batch
Epoch: 2/20...  Training Step: 311...  Training loss: 2.2322...  4.4986 sec/batch
Epoch: 2/20...  Training Step: 312...  Training loss: 2.2289...  4.4999 sec/batch
Epoch: 2/20...  Training Step: 313...  Training loss: 2.2248...  4.5678 sec/batch
Epoch: 2/20...  Training Step: 314...  Training loss: 2.2011...  4.5938 sec/batch
Epoch: 2/20...  

Epoch: 3/20...  Training Step: 403...  Training loss: 2.1066...  4.4684 sec/batch
Epoch: 3/20...  Training Step: 404...  Training loss: 2.1035...  4.5093 sec/batch
Epoch: 3/20...  Training Step: 405...  Training loss: 2.1393...  4.5302 sec/batch
Epoch: 3/20...  Training Step: 406...  Training loss: 2.0956...  4.5808 sec/batch
Epoch: 3/20...  Training Step: 407...  Training loss: 2.0807...  4.4858 sec/batch
Epoch: 3/20...  Training Step: 408...  Training loss: 2.0788...  4.4776 sec/batch
Epoch: 3/20...  Training Step: 409...  Training loss: 2.1013...  4.4623 sec/batch
Epoch: 3/20...  Training Step: 410...  Training loss: 2.1276...  4.4734 sec/batch
Epoch: 3/20...  Training Step: 411...  Training loss: 2.0891...  4.5274 sec/batch
Epoch: 3/20...  Training Step: 412...  Training loss: 2.0738...  4.5097 sec/batch
Epoch: 3/20...  Training Step: 413...  Training loss: 2.0831...  4.5857 sec/batch
Epoch: 3/20...  Training Step: 414...  Training loss: 2.1309...  4.7165 sec/batch
Epoch: 3/20...  

Epoch: 3/20...  Training Step: 503...  Training loss: 1.9799...  4.4686 sec/batch
Epoch: 3/20...  Training Step: 504...  Training loss: 1.9893...  4.5162 sec/batch
Epoch: 3/20...  Training Step: 505...  Training loss: 1.9848...  4.5407 sec/batch
Epoch: 3/20...  Training Step: 506...  Training loss: 1.9801...  4.4932 sec/batch
Epoch: 3/20...  Training Step: 507...  Training loss: 1.9833...  4.4973 sec/batch
Epoch: 3/20...  Training Step: 508...  Training loss: 1.9643...  4.4782 sec/batch
Epoch: 3/20...  Training Step: 509...  Training loss: 1.9672...  4.4766 sec/batch
Epoch: 3/20...  Training Step: 510...  Training loss: 1.9576...  4.5044 sec/batch
Epoch: 3/20...  Training Step: 511...  Training loss: 1.9511...  4.4931 sec/batch
Epoch: 3/20...  Training Step: 512...  Training loss: 1.9303...  4.5350 sec/batch
Epoch: 3/20...  Training Step: 513...  Training loss: 1.9675...  4.4816 sec/batch
Epoch: 3/20...  Training Step: 514...  Training loss: 1.9669...  4.4329 sec/batch
Epoch: 3/20...  

Epoch: 4/20...  Training Step: 603...  Training loss: 1.9236...  4.5914 sec/batch
Epoch: 4/20...  Training Step: 604...  Training loss: 1.8946...  4.6914 sec/batch
Epoch: 4/20...  Training Step: 605...  Training loss: 1.8710...  4.6644 sec/batch
Epoch: 4/20...  Training Step: 606...  Training loss: 1.8659...  4.5268 sec/batch
Epoch: 4/20...  Training Step: 607...  Training loss: 1.8850...  4.5437 sec/batch
Epoch: 4/20...  Training Step: 608...  Training loss: 1.9239...  4.5478 sec/batch
Epoch: 4/20...  Training Step: 609...  Training loss: 1.8855...  4.5424 sec/batch
Epoch: 4/20...  Training Step: 610...  Training loss: 1.8621...  4.5847 sec/batch
Epoch: 4/20...  Training Step: 611...  Training loss: 1.8846...  4.6060 sec/batch
Epoch: 4/20...  Training Step: 612...  Training loss: 1.9268...  4.5377 sec/batch
Epoch: 4/20...  Training Step: 613...  Training loss: 1.8793...  4.4784 sec/batch
Epoch: 4/20...  Training Step: 614...  Training loss: 1.8818...  4.4722 sec/batch
Epoch: 4/20...  

Epoch: 4/20...  Training Step: 703...  Training loss: 1.8258...  4.4787 sec/batch
Epoch: 4/20...  Training Step: 704...  Training loss: 1.8212...  4.5168 sec/batch
Epoch: 4/20...  Training Step: 705...  Training loss: 1.8084...  4.4348 sec/batch
Epoch: 4/20...  Training Step: 706...  Training loss: 1.8077...  4.4265 sec/batch
Epoch: 4/20...  Training Step: 707...  Training loss: 1.8004...  4.4295 sec/batch
Epoch: 4/20...  Training Step: 708...  Training loss: 1.8083...  4.4724 sec/batch
Epoch: 4/20...  Training Step: 709...  Training loss: 1.7778...  4.4533 sec/batch
Epoch: 4/20...  Training Step: 710...  Training loss: 1.7792...  4.5810 sec/batch
Epoch: 4/20...  Training Step: 711...  Training loss: 1.8154...  4.5741 sec/batch
Epoch: 4/20...  Training Step: 712...  Training loss: 1.8090...  4.4895 sec/batch
Epoch: 4/20...  Training Step: 713...  Training loss: 1.8157...  4.4698 sec/batch
Epoch: 4/20...  Training Step: 714...  Training loss: 1.8179...  4.5013 sec/batch
Epoch: 4/20...  

Epoch: 5/20...  Training Step: 803...  Training loss: 1.7150...  4.6049 sec/batch
Epoch: 5/20...  Training Step: 804...  Training loss: 1.7274...  4.5218 sec/batch
Epoch: 5/20...  Training Step: 805...  Training loss: 1.7459...  4.4815 sec/batch
Epoch: 5/20...  Training Step: 806...  Training loss: 1.7736...  4.4943 sec/batch
Epoch: 5/20...  Training Step: 807...  Training loss: 1.7364...  4.5007 sec/batch
Epoch: 5/20...  Training Step: 808...  Training loss: 1.7187...  4.5630 sec/batch
Epoch: 5/20...  Training Step: 809...  Training loss: 1.7506...  4.5734 sec/batch
Epoch: 5/20...  Training Step: 810...  Training loss: 1.7723...  4.5798 sec/batch
Epoch: 5/20...  Training Step: 811...  Training loss: 1.7429...  4.4894 sec/batch
Epoch: 5/20...  Training Step: 812...  Training loss: 1.7542...  4.4807 sec/batch
Epoch: 5/20...  Training Step: 813...  Training loss: 1.7261...  4.4686 sec/batch
Epoch: 5/20...  Training Step: 814...  Training loss: 1.7662...  4.4367 sec/batch
Epoch: 5/20...  

Epoch: 5/20...  Training Step: 903...  Training loss: 1.6891...  4.5482 sec/batch
Epoch: 5/20...  Training Step: 904...  Training loss: 1.6888...  4.5915 sec/batch
Epoch: 5/20...  Training Step: 905...  Training loss: 1.6724...  4.5266 sec/batch
Epoch: 5/20...  Training Step: 906...  Training loss: 1.6711...  4.5171 sec/batch
Epoch: 5/20...  Training Step: 907...  Training loss: 1.6548...  4.6653 sec/batch
Epoch: 5/20...  Training Step: 908...  Training loss: 1.6501...  4.5243 sec/batch
Epoch: 5/20...  Training Step: 909...  Training loss: 1.6812...  4.5956 sec/batch
Epoch: 5/20...  Training Step: 910...  Training loss: 1.6850...  4.5184 sec/batch
Epoch: 5/20...  Training Step: 911...  Training loss: 1.6728...  4.5186 sec/batch
Epoch: 5/20...  Training Step: 912...  Training loss: 1.6705...  4.4829 sec/batch
Epoch: 5/20...  Training Step: 913...  Training loss: 1.6776...  4.4817 sec/batch
Epoch: 5/20...  Training Step: 914...  Training loss: 1.6434...  4.5417 sec/batch
Epoch: 5/20...  

#### Saved checkpoints

Read up on saving and loading checkpoints here: https://www.tensorflow.org/programmers_guide/variables

In [ ]:
tf.train.get_checkpoint_state('checkpoints')

## Sampling

Now that the network is trained, we'll can use it to generate new text. The idea is that we pass in a character, then the network will predict the next character. We can use the new one, to predict the next one. And we keep doing this to generate all new text. I also included some functionality to prime the network with some text by passing in a string and building up a state from that.

The network gives us predictions for each character. To reduce noise and make things a little less random, I'm going to only choose a new character from the top N most likely characters.



In [ ]:
def pick_top_n(preds, vocab_size, top_n=5):
    p = np.squeeze(preds)
    p[np.argsort(p)[:-top_n]] = 0
    p = p / np.sum(p)
    c = np.random.choice(vocab_size, 1, p=p)[0]
    return c

In [ ]:
def sample(checkpoint, n_samples, lstm_size, vocab_size, prime="The "):
    samples = [c for c in prime]
    model = CharRNN(len(vocab), lstm_size=lstm_size, sampling=True)
    saver = tf.train.Saver()
    with tf.Session() as sess:
        saver.restore(sess, checkpoint)
        new_state = sess.run(model.initial_state)
        for c in prime:
            x = np.zeros((1, 1))
            x[0,0] = vocab_to_int[c]
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)

        c = pick_top_n(preds, len(vocab))
        samples.append(int_to_vocab[c])

        for i in range(n_samples):
            x[0,0] = c
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)

            c = pick_top_n(preds, len(vocab))
            samples.append(int_to_vocab[c])
        
    return ''.join(samples)

Here, pass in the path to a checkpoint and sample from the network.

In [ ]:
tf.train.latest_checkpoint('checkpoints')

In [ ]:
checkpoint = tf.train.latest_checkpoint('checkpoints')
samp = sample(checkpoint, 2000, lstm_size, len(vocab), prime="Far")
print(samp)

In [ ]:
checkpoint = 'checkpoints/i200_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)

In [ ]:
checkpoint = 'checkpoints/i600_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)

In [ ]:
checkpoint = 'checkpoints/i1200_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)